name: Building, running Code and deploying .JAR file to Cloud

on:
  push:
    branches:
      - Acceptance
  pull_request:
    branches:
      - Acceptance

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with Maven
        run: mvn -B package test --file pom.xml

      - name: JAR Snapshot Uploading
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: JabberPoint-Software-Quality-1.0-ACCEPTANCE-SNAPSHOT
          path: /home/runner/work/JabberPoint-SoftwareQuality/JabberPoint-SoftwareQuality/target/

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{ secrets.JAR_DEPLOYMENT_EMAIL }}
          credentials_json: ${{ secrets.JAR_DEPLOYMENT_KEY }}
          project_id: github-actions-jar-deployment

      - name: List contents of /home/runner/work/
        run: ls /home/runner/work/JabberPoint-SoftwareQuality/JabberPoint-SoftwareQuality/target/

        with:
          path: /home/runner/work/JabberPoint-SoftwareQuality/JabberPoint-SoftwareQuality/target/JabberPoint-Software-Quality-1.0-ACCEPTANCE-SNAPSHOT.jar
          destination: software-quality-jar/acceptance/
