name: Checking Code Style(NHL Stenden Conventions)
on:
  push:
    branches:
      - Test
  pull_request:
    branches:
      - Test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Start xvfb
        run: |
          Xvfb :99 -ac &
          export DISPLAY=:99

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          DISPLAY: :99

      - name: Run tests with Maven
        run: mvn -B package test --file pom.xml
        env:
          DISPLAY: :99

      - name: Check Code Style
        run: mvn checkstyle:check
        env:
          DISPLAY: :99
